services:
  mysql:
    container_name: clinica_vet-mysql
    image: mysql:9.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clinica_vet
      MYSQL_USER: app
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data: